routes/web.php
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('front.')->group(function(){
	// Route::get('index','FrontController@index')->name('index');
	Route::get('/','FrontController@index')->name('index');
	Route::get('subastas','FrontController@subastas')->name('subastas');
	Route::get('subasta/{id}','FrontController@subasta')->name('subasta');
	Route::get('nosotros','FrontController@aboutus')->name('aboutus');
	//Route::get('espacios','FrontController@espacios')->name('espacios');
	Route::get('espacio/{id}','FrontController@espacio')->name('espacio');
	Route::get('productos/{slug?}','FrontController@productos')->name('productos');
	Route::get('producto/{id}','FrontController@producto')->name('producto');
	Route::get('contacto','FrontController@contact')->name('contact');
	Route::post('contacto','FrontController@mailcontact')->name('mailcontact');
	Route::get('garantias','FrontController@garantias')->name('garantias');
	Route::get('aviso-de-privacidad','FrontController@aviso')->name('aviso');
	Route::get('metodos-de-pago','FrontController@pagos')->name('pagos');
	Route::get('devoluciones','FrontController@devoluciones')->name('devoluciones');
	Route::get('terminos-y-condiciones','FrontController@tyc')->name('tyc');
	Route::get('faq','FrontController@preguntas')->name('faq');
	Route::post('puja','PujaController@store')->name('puja.store');
	Route::post('newslatter','NewslatterController@store')->name('save');
});

// vistas del dashboard del usuario
Route::prefix('dashboard')->name('dash.')->group(function(){
	Route::get('/','HomeController@index')->name('index');
	Route::get('subastas','HomeController@subastas')->name('subastas');
	Route::get('subasta/detalle/{id}','HomeController@subastaDetail')->name('subastaDetail');
	Route::get('perfil','HomeController@perfil')->name('perfil');
	Route::post('update','HomeController@updatePass')->name('updatePass');

	Route::prefix('mis-compras')->name('compras.')->group(function(){
		Route::get('/','HomeController@compras')->name('index');
		Route::get('detalle/{id}','HomeController@detalle')->name('detalle');
	});

	Route::name('profile.')->group(function(){
		Route::post('store','DomicilioController@store')->name('store');
	});


	Route::get('orden/{uuid}','HomeController@orden')->name('orden');
	Route::get('orden-sub/{uuid}','HomeController@ordenSub')->name('ordenSub');
});

Route::prefix('paypal')->name('paypal.')->group(function(){
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPal')->name('paypalpay');
	Route::get('/status', 'PaymentController@payPalStatus')->name('paypalstatus');
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPalSub')->name('paypalpay2');
});

Route::prefix('conekta')->name('conekta.')->group(function(){
	Route::get('/{uid}', 'Payment2Controller@getCard')->name('card');
	Route::post('payment', 'Payment2Controller@statusPay')->name('statusPay');
	// Route::get('/pay/{uid}', 'PaymentController@payWithConekta')->name('conektapay');
	// Route::get('/status', 'PaymentController@conektaStatus')->name('conektastatus');
});

// Route::get('/', function () {
//     return view('layouts.front');
// });

// rutas al admin
Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::name('admin.')->group(function(){
		Route::get('/', 'HomeController@index')->name('home');
		Route::namespace('Auth')->group(function(){
			Route::get('/login', 'LoginController@showLoginForm')->name('login');
			Route::post('/login', 'LoginController@login');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
	});

// rutas al admin configuraciones
// controllers dentro de Controllers/Admin/
	Route::prefix('config')->name('config.')->group(function(){
		Route::get('index','ConfiguracionController@index')->name('index');
		Route::get('general','ConfiguracionController@general')->name('general');
		Route::get('contacto','ConfiguracionController@contact')->name('contact');
		Route::get('textos','ConfiguracionController@textos')->name('textos');
		Route::get('nosotros','ConfiguracionController@about')->name('about');
		Route::put('nosotros/{id}','ConfiguracionController@aboutimg')->name('aboutimg');
		Route::post('nosotros','ConfiguracionController@aboutgal')->name('aboutgal');
		Route::get('subasta','ConfiguracionController@subastagal')->name('subastagal');
		Route::post('subasta','ConfiguracionController@savesubastagal')->name('savesubastagal');



	});
	// Route::prefix('config')->name('config.')->group(function(){
	// 	Route::get('index','ConfiguracionController@index')->name('index');
	// });
});

// rutas al admin configuraciones
// controllers dentro de Controllers/
Route::prefix('admin')->group(function(){
	Route::prefix('config')->name('config.')->group(function(){
		Route::prefix('colores')->name('color.')->group(function(){
			Route::get('/','ColorController@index')->name('index');
			Route::post('/','ColorController@store')->name('store');
			Route::get('editar/{id}','ColorController@edit')->name('edit');
			Route::put('{id}','ColorController@update')->name('update');
			Route::delete('/','ColorController@destroy')->name('delete');
		});

		Route::prefix('sliders')->name('slider.')->group(function(){
			Route::get('/','CarruselController@index')->name('index');
			Route::post('/','CarruselController@store')->name('store');
			Route::delete('/','CarruselController@destroy')->name('delete');
		});



		Route::prefix('spaces')->name('space.')->group(function(){
			Route::get('/','EspacioController@index')->name('index');
			Route::get('detalle/{id}','EspacioController@show')->name('show');
			Route::post('/','EspacioController@store')->name('store');
			Route::delete('/','EspacioController@destroy')->name('delete');

		});

		Route::prefix('sucursales')->name('sucursal.')->group(function(){
			Route::get('/','SucursalController@index')->name('index');
			Route::get('nueva','SucursalController@create')->name('create');
			Route::post('/','SucursalController@store')->name('store');
			Route::get('{id}','SucursalController@edit')->name('edit');
			Route::put('{id}','SucursalController@update')->name('update');
			Route::delete('/','SucursalController@destroy')->name('delete');

		});


		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','EspacioproductoController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});

		Route::prefix('politicas')->name('politica.')->group(function(){
			Route::get('/','PoliticaController@index')->name('index');
			Route::put('/{id}','PoliticaController@update')->name('update');
		});

		Route::prefix('faq')->name('faq.')->group(function(){
			Route::get('/','FaqController@index')->name('index');
			Route::get('nueva','FaqController@create')->name('create');
			Route::post('/','FaqController@store')->name('store');
			Route::get('{id}','FaqController@edit')->name('edit');
			Route::put('{id}','FaqController@update')->name('update');
			Route::delete('/','FaqController@destroy')->name('delete');
		});

		Route::prefix('dimension')->name('size.')->group(function(){
			Route::get('/','CategTamanoController@index')->name('index');
			Route::post('/','CategTamanoController@store')->name('store');
			Route::delete('/','CategTamanoController@destroy')->name('delete');

			Route::name('dimension.')->group(function(){
				Route::get('{slug}','SizeController@index')->name('index');
				Route::post('t','SizeController@store')->name('store');
				Route::delete('t','SizeController@destroy')->name('delete');
			});
		});

		Route::prefix('cupones')->name('cupons.')->group(function(){
			Route::get('/','CuponController@index')->name('index');
		});

	});

	Route::prefix('productos')->name('productos.')->group(function(){
		Route::get('/','ProductoController@index')->name('index');
		Route::get('nuevo','ProductoController@create')->name('create');
		Route::post('nuevo','ProductoController@store')->name('store');
		Route::get('detalle/{id}','ProductoController@show')->name('show');
		Route::get('{id}','ProductoController@edit')->name('edit');
		Route::put('{id}','ProductoController@update')->name('update');
		Route::post('delete','ProductoController@destroy')->name('delete');

		Route::name('pic.')->group(function(){
			Route::post('newpic/{id}','ProductosPhotoController@store')->name('store');
			Route::delete('/','ProductosPhotoController@destroy')->name('delete');
		});

		Route::name('version.')->group(function(){
			Route::post('newpv/{id}','ProductoVersionPhotoController@store')->name('store');
			Route::delete('pv/','ProductoVersionPhotoController@destroy')->name('delete');
		});

		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','ProductoRelacionController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});
	});


		Route::prefix('galeriasub')->name('galeriasub.')->group(function(){
			Route::delete('/','GaleriaSubastaController@destroy')->name('delete');
		});

	/*Route::prefix('config2')->name('config2.')->group(function(){
		Route::get('/','Configuracion2Controller@index')->name('index');
		Route::get('nuevo','Configuracion2Controller@create')->name('create');
		Route::post('/','Configuracion2Controller@store')->name('store');
		Route::get('/{id}','Configuracion2Controller@show')->name('show');
	});*/

	Route::prefix('categorias')->name('categ.')->group(function(){
		Route::get('/','CategoriaController@index')->name('index');
		Route::post('/','CategoriaController@store')->name('store');
		Route::get('/{id}','CategoriaController@show')->name('show');
	});

	Route::prefix('subastas')->name('subastas.')->group(function(){
		Route::get('/','SubastaController@index')->name('index');

resources/views/layouts/partials_ad/header.blade.php
<header>
	@include('layouts.partials_ad.sidebar')

	<nav class="navbar fixed-top navbar-expand-lg scrolling-navbar double-nav">

		<div class="float-left">
			<a href="#" data-activates="slide-out" class="button-collapse"><i class="fas fa-bars"></i></a>
		</div>

		<!-- Breadcrumb -->
		<div class="breadcrumb-dn mr-auto">
			<p>Dashboard v.1</p>
		</div>

		<div class="d-flex change-mode">
			<ul class="nav navbar-nav nav-flex-icons ml-auto">
				<li class="nav-item dropdown notifications-nav d-none">
					<a class="nav-link dropdown-toggle waves-effect" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="badge red">3</span> <i class="fas fa-bell"></i>
						<span class="d-none d-md-inline-block">Notificaciones</span>
					</a>
					<div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="#">
							<i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
							<span>New order received</span>
							<span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 13 min</span>
						</a>
						<a class="dropdown-item" href="#">
							<i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
							<span>New order received</span>
							<span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 33 min</span>
						</a>
						<a class="dropdown-item" href="#">
							<i class="fas fa-chart-line mr-2" aria-hidden="true"></i>
							<span>Your campaign is about to end</span>
							<span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 53 min</span>
						</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle waves-effect" href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fas fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Perfil</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
						<a class="dropdown-item" href="#">Mi cuenta</a>
						<a class="dropdown-item" href="{{ route('admin.logout') }}"
							 onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
								{{ __('Salir') }}
						</a>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
								@csrf
						</form>
					</div>
				</li>
			</ul>
		</div>
	</nav>

</header>

resources/views/layouts/partials_ad/sidebar.blade.php
<div id="slide-out" class="side-nav sn-bg-5 fixed">
	<ul class="custom-scrollbar">
	<li class="logo-sn waves-effect py-3">
			<div class="text-center">
				<a href="#" class="pl-0">
					<img class="img-fluid h-100" src="{{asset('img/design/logo_woz.png')}}">
				</a>
			</div>
		</li>
		{{-- <li>
			<ul class="collapsible collapsible-accordion">
				<li class="{{ (request()->is('admin/config')) ? 'active' : '' }}">
					<a class="collapsible-header waves-effect arrow-r {{ (request()->is('admin/config')) ? 'active' : '' }}">
						<i class="w-fa fas fa-cog"></i>
						Configuración
						<i class="fas fa-angle-down rotate-icon"></i>
					</a>
					<div class="collapsible-body">
						<ul>
							<li>
								<a href="../dashboards/v-1.html" class="waves-effect">Version 1</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="{{ (request()->is('admin/productos')) ? 'active' : '' }}">
					<a class="collapsible-header waves-effect arrow-r {{ (request()->is('admin/productos')) ? 'active' : '' }}">
						<i class="fas fa-box-open"></i>
						Productos
						<i class="fas fa-angle-down rotate-icon"></i>
					</a>
					<div class="collapsible-body">
						<ul>
							<li>
								<a href="{{route('productos.create')}}" class="waves-effect">Nuevo</a>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a class="collapsible-header waves-effect arrow-r">
						<i class="w-fa fas fa-map"></i>Maps<i class="fas fa-angle-down rotate-icon"></i>
					</a>
					<div class="collapsible-body">
						<ul>
							<li>
								<a href="../maps/google.html" class="waves-effect">Google Maps</a>
							</li>
							<li>
								<a href="../maps/full.html" class="waves-effect">Full screen map</a>
							</li>
							<li>
								<a href="../maps/vector.html" class="waves-effect">Vector world map</a>
							</li>
						</ul>
					</div>
				</li>
			</li> --}}
			<li>
				<ul class="collapsible collapsible-accordion">
					<li>
						<a href="{{ route('pedidos.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/pedidos')) ? 'active' : '' }}"><i class="w-fa fas fa-file-invoice-dollar"></i>Pedidos</a>
					</li>
					<li class="{{ (request()->is('admin/config')) ? 'active' : '' }}">
						<a class="collapsible-header waves-effect arrow-r">
							<i class="fas fa-gavel"></i>
							Subastas
							<i class="fas fa-angle-down rotate-icon"></i>
						</a>
						<div class="collapsible-body">
							<ul>
								<li>
									<a href="{{ route('subastas.orden.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/subastas/ordenes')) ? 'active' : '' }}"> Panel ubastas</a>
								</li>
								<li>
									<a href="{{ route('subastas.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/subastas')) ? 'active' : '' }}"> Subastas</a>
								</li>
							</ul>
						</div>
					</li>
					{{-- <li>
						<a href="{{ route('subastas.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/subastas')) ? 'active' : '' }}"> <i class="fas fa-gavel"></i>Subastas</a>
					</li> --}}
					<li>
						<a href="{{ route('productos.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/productos')) ? 'active' : '' }}"><i class="fas fa-box-open"></i>Productos</a>
					</li>
					<li>
						<a href="../alerts/alerts.html" class="collapsible-header waves-effect"><i class="w-fa far fa-bell"></i>Alerts</a>
					</li>
					<li>
						<a href="{{ route('clientes.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/clientes')) ? 'active' : '' }}"><i class="w-fa fas fa-users"></i>Clientes</a>
					</li>
					<li>
						<a href="{{ route('newslatters.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/newslatters')) ? 'active' : '' }}"><i class="fab fa-mailchimp"></i>Newslatter</a>
					</li>

					<li>
						<a href="{{ route('config.index') }}" class="collapsible-header waves-effect {{ (request()->is('admin/config')) ? 'active' : '' }}"><i class="w-fa fas fa-cog"></i>Configuración</a>
					</li>

				</ul>
			</li>
		</ul>

	<div class="sidenav-bg mask-strong"></div>

	<div class="fixed-action-btn clearfix d-none" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-lg red">
			<i class="fas fa-pencil-alt"></i>
		</a>
		<ul class="list-unstyled">
			<li><a class="btn-floating red"><i class="fas fa-star"></i></a></li>
			<li><a class="btn-floating yellow darken-1"><i class="fas fa-user"></i></a></li>
			<li><a class="btn-floating green"><i class="fas fa-envelope"></i></a></li>
			<li><a class="btn-floating blue"><i class="fas fa-shopping-cart"></i></a></li>
		</ul>
	</div>
</div>

resources/views/layouts/partials_ad/sidebar_ex.blade.php
		<div id="slide-out" class="side-nav sn-bg-4 fixed">
			<ul class="custom-scrollbar">
				<li class="logo-sn waves-effect py-3">
					<div class="text-center">
						<a href="#" class="pl-0"><img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png"></a>
					</div>
				</li>
				<li>
					<form class="search-form" role="search">
						<div class="md-form mt-0 waves-light">
							<input type="text" class="form-control py-2" placeholder="Search">
						</div>
					</form>
				</li>
				<li>
					<ul class="collapsible collapsible-accordion">

						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-tachometer-alt"></i>Dashboards<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../dashboards/v-1.html" class="waves-effect">Version 1</a>
									</li>
									<li>
										<a href="../dashboards/v-2.html" class="waves-effect">Version 2</a>
									</li>
									<li>
										<a href="../dashboards/v-3.html" class="waves-effect">Version 3</a>
									</li>
									<li>
										<a href="../dashboards/v-4.html" class="waves-effect">Version 4</a>
									</li>
									<li>
										<a href="../dashboards/v-5.html" class="waves-effect">Version 5</a>
									</li>
									<li>
										<a href="../dashboards/v-6.html" class="waves-effect">Version 6</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-image"></i>Pages<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../pages/login.html" class="waves-effect">Login</a>
									</li>
									<li>
										<a href="../pages/register.html" class="waves-effect">Register</a>
									</li>
									<li>
										<a href="../pages/pricing.html" class="waves-effect">Pricing</a>
									</li>
									<li>
										<a href="../pages/about.html" class="waves-effect">About us</a>
									</li>
									<li>
										<a href="../pages/single.html" class="waves-effect">Single post</a>
									</li>
									<li>
										<a href="../pages/post.html" class="waves-effect">Post listing</a>
									</li>
									<li>
										<a href="../pages/landing.html" class="waves-effect">Landing page</a>
									</li>
									<li>
										<a href="../pages/customers.html" class="waves-effect">Customers</a>
									</li>
									<li>
										<a href="../pages/invoice.html" class="waves-effect">Invoice</a>
									</li>
									<li>
										<a href="../pages/page-creator.html" class="waves-effect">Page Creator</a>
									</li>
									<li>
										<a href="../pages/support.html" class="waves-effect">Support</a>
									</li>
									<li>
										<a href="../pages/chat.html" class="waves-effect">Chat</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-user"></i>Profile<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../profile/basic-1.html" class="waves-effect">Basic 1</a>
									</li>
									<li>
										<a href="../profile/basic-2.html" class="waves-effect">Basic 2</a>
									</li>
									<li>
										<a href="../profile/extended.html" class="waves-effect">Extended</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fab fa-css3"></i>CSS<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../css/grid.html" class="waves-effect">Grid system</a>
									</li>
									<li>
										<a href="../css/media.html" class="waves-effect">Media object</a>
									</li>
									<li>
										<a href="../css/utilities.html" class="waves-effect">Utilities / helpers</a>
									</li>
									<li>
										<a href="../css/code.html" class="waves-effect">Code</a>
									</li>
									<li>
										<a href="../css/icons.html" class="waves-effect">Icons</a>
									</li>
									<li>
										<a href="../css/images.html" class="waves-effect">Images</a>
									</li>
									<li>
										<a href="../css/typography.html" class="waves-effect">Typography</a>
									</li>
									<li>
										<a href="../css/animations.html" class="waves-effect">Animations</a>
									</li>
									<li>
										<a href="../css/colors.html" class="waves-effect">Colors</a>
									</li>
									<li>
										<a href="../css/hover.html" class="waves-effect">Hover effects</a>
									</li>
									<li>
										<a href="../css/masks.html" class="waves-effect">Masks</a>
									</li>
									<li>
										<a href="../css/shadows.html" class="waves-effect">Shadows</a>
									</li>
									<li>
										<a href="../css/skins.html" class="waves-effect">Skins</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-th"></i>Components<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../components/buttons.html" class="waves-effect">Buttons</a>
									</li>
									<li>
										<a href="../components/cards.html" class="waves-effect">Cards</a>
									</li>
									<li>
										<a href="../components/collapse.html" class="waves-effect">Collapse</a>
									</li>
									<li>
										<a href="../components/date.html" class="waves-effect">Date picker</a>
									</li>
									<li>
										<a href="../components/list.html" class="waves-effect">List group</a>
									</li>
									<li>
										<a href="../components/panels.html" class="waves-effect">Panels</a>
									</li>
									<li>
										<a href="../components/pagination.html" class="waves-effect">Pagination</a>
									</li>
									<li>
										<a href="../components/popovers.html" class="waves-effect">Popovers</a>
									</li>
									<li>
										<a href="../components/progress.html" class="waves-effect">Progress bars</a>
									</li>
									<li>
										<a href="../components/stepper.html" class="waves-effect">Stepper</a>
									</li>
									<li>
										<a href="../components/tabs.html" class="waves-effect">Tabs & pills</a>
									</li>
									<li>
										<a href="../components/tags.html" class="waves-effect">Tags, labels & badges</a>
									</li>
									<li>
										<a href="../components/time.html" class="waves-effect">Time picker</a>
									</li>
									<li>
										<a href="../components/tooltips.html" class="waves-effect">Tooltips</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa far fa-check-square"></i>Forms<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../forms/basic.html" class="waves-effect">Basic</a>
									</li>
									<li>
										<a href="../forms/extended.html" class="waves-effect">Extended</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-table"></i>Tables<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../tables/basic.html" class="waves-effect">Basic</a>
									</li>
									<li>
										<a href="../tables/extended.html" class="waves-effect">Extended</a>
									</li>
									<li>
										<a href="../tables/datatables.html" class="waves-effect">DataTables.net</a>
									</li>
								</ul>
							</div>
						</li>
						<li>
							<a class="collapsible-header waves-effect arrow-r">
								<i class="w-fa fas fa-map"></i>Maps<i class="fas fa-angle-down rotate-icon"></i>
							</a>
							<div class="collapsible-body">
								<ul>
									<li>
										<a href="../maps/google.html" class="waves-effect">Google Maps</a>
									</li>
									<li>
										<a href="../maps/full.html" class="waves-effect">Full screen map</a>
									</li>
									<li>
										<a href="../maps/vector.html" class="waves-effect">Vector world map</a>
									</li>
								</ul>
							</div>
						</li>

						<li>
							<a href="../alerts/alerts.html" class="collapsible-header waves-effect"><i class="w-fa far fa-bell"></i>Alerts</a>
						</li>
						<li>
							<a href="../modals/modals.html" class="collapsible-header waves-effect"><i class="w-fa fas fa-bolt"></i>Modals</a>
						</li>
						<li>
							<a href="../charts/charts.html" class="collapsible-header waves-effect"><i class="w-fa fas fa-chart-pie"></i>Charts</a>
						</li>
						<li>
							<a href="../calendar/calendar.html" class="collapsible-header waves-effect"><i class="w-fa far fa-calendar-check"></i>Calendar</a>
						</li>
						<li>
							<a href="../sections/sections.html" class="collapsible-header waves-effect"><i class="w-fa fas fa-th-large"></i>Sections</a>
						</li>
					</ul>
				</li>
			</ul>
			<div class="sidenav-bg mask-strong"></div>
		</div>