routes/web.php
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('front.')->group(function(){
	// Route::get('index','FrontController@index')->name('index');
	Route::get('/','FrontController@index')->name('index');
	Route::get('subastas','FrontController@subastas')->name('subastas');
	Route::get('subasta/{id}','FrontController@subasta')->name('subasta');
	Route::get('nosotros','FrontController@aboutus')->name('aboutus');
	//Route::get('espacios','FrontController@espacios')->name('espacios');
	Route::get('espacio/{id}','FrontController@espacio')->name('espacio');
	Route::get('productos/{slug?}','FrontController@productos')->name('productos');
	Route::get('producto/{id}','FrontController@producto')->name('producto');
	Route::get('contacto','FrontController@contact')->name('contact');
	Route::post('contacto','FrontController@mailcontact')->name('mailcontact');
	Route::get('garantias','FrontController@garantias')->name('garantias');
	Route::get('aviso-de-privacidad','FrontController@aviso')->name('aviso');
	Route::get('metodos-de-pago','FrontController@pagos')->name('pagos');
	Route::get('devoluciones','FrontController@devoluciones')->name('devoluciones');
	Route::get('terminos-y-condiciones','FrontController@tyc')->name('tyc');
	Route::get('faq','FrontController@preguntas')->name('faq');
	Route::post('puja','PujaController@store')->name('puja.store');
	Route::post('newslatter','NewslatterController@store')->name('save');
});

// vistas del dashboard del usuario
Route::prefix('dashboard')->name('dash.')->group(function(){
	Route::get('/','HomeController@index')->name('index');
	Route::get('subastas','HomeController@subastas')->name('subastas');
	Route::get('subasta/detalle/{id}','HomeController@subastaDetail')->name('subastaDetail');
	Route::get('perfil','HomeController@perfil')->name('perfil');
	Route::post('update','HomeController@updatePass')->name('updatePass');

	Route::prefix('mis-compras')->name('compras.')->group(function(){
		Route::get('/','HomeController@compras')->name('index');
		Route::get('detalle/{id}','HomeController@detalle')->name('detalle');
	});

	Route::name('profile.')->group(function(){
		Route::post('store','DomicilioController@store')->name('store');
	});


	Route::get('orden/{uuid}','HomeController@orden')->name('orden');
	Route::get('orden-sub/{uuid}','HomeController@ordenSub')->name('ordenSub');
});

Route::prefix('paypal')->name('paypal.')->group(function(){
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPal')->name('paypalpay');
	Route::get('/status', 'PaymentController@payPalStatus')->name('paypalstatus');
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPalSub')->name('paypalpay2');
});

Route::prefix('conekta')->name('conekta.')->group(function(){
	Route::get('/{uid}', 'Payment2Controller@getCard')->name('card');
	Route::post('payment', 'Payment2Controller@statusPay')->name('statusPay');
	// Route::get('/pay/{uid}', 'PaymentController@payWithConekta')->name('conektapay');
	// Route::get('/status', 'PaymentController@conektaStatus')->name('conektastatus');
});

// Route::get('/', function () {
//     return view('layouts.front');
// });

// rutas al admin
Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::name('admin.')->group(function(){
		Route::get('/', 'HomeController@index')->name('home');
		Route::namespace('Auth')->group(function(){
			Route::get('/login', 'LoginController@showLoginForm')->name('login');
			Route::post('/login', 'LoginController@login');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
	});

// rutas al admin configuraciones
// controllers dentro de Controllers/Admin/
	Route::prefix('config')->name('config.')->group(function(){
		Route::get('index','ConfiguracionController@index')->name('index');
		Route::get('general','ConfiguracionController@general')->name('general');
		Route::get('contacto','ConfiguracionController@contact')->name('contact');
		Route::get('textos','ConfiguracionController@textos')->name('textos');
		Route::get('nosotros','ConfiguracionController@about')->name('about');
		Route::put('nosotros/{id}','ConfiguracionController@aboutimg')->name('aboutimg');
		Route::post('nosotros','ConfiguracionController@aboutgal')->name('aboutgal');
		Route::get('subasta','ConfiguracionController@subastagal')->name('subastagal');
		Route::post('subasta','ConfiguracionController@savesubastagal')->name('savesubastagal');



	});
	// Route::prefix('config')->name('config.')->group(function(){
	// 	Route::get('index','ConfiguracionController@index')->name('index');
	// });
});

// rutas al admin configuraciones
// controllers dentro de Controllers/
Route::prefix('admin')->group(function(){
	Route::prefix('config')->name('config.')->group(function(){
		Route::prefix('colores')->name('color.')->group(function(){
			Route::get('/','ColorController@index')->name('index');
			Route::post('/','ColorController@store')->name('store');
			Route::get('editar/{id}','ColorController@edit')->name('edit');
			Route::put('{id}','ColorController@update')->name('update');
			Route::delete('/','ColorController@destroy')->name('delete');
		});

		Route::prefix('sliders')->name('slider.')->group(function(){
			Route::get('/','CarruselController@index')->name('index');
			Route::post('/','CarruselController@store')->name('store');
			Route::delete('/','CarruselController@destroy')->name('delete');
		});



		Route::prefix('spaces')->name('space.')->group(function(){
			Route::get('/','EspacioController@index')->name('index');
			Route::get('detalle/{id}','EspacioController@show')->name('show');
			Route::post('/','EspacioController@store')->name('store');
			Route::delete('/','EspacioController@destroy')->name('delete');

		});

		Route::prefix('sucursales')->name('sucursal.')->group(function(){
			Route::get('/','SucursalController@index')->name('index');
			Route::get('nueva','SucursalController@create')->name('create');
			Route::post('/','SucursalController@store')->name('store');
			Route::get('{id}','SucursalController@edit')->name('edit');
			Route::put('{id}','SucursalController@update')->name('update');
			Route::delete('/','SucursalController@destroy')->name('delete');

		});


		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','EspacioproductoController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});

		Route::prefix('politicas')->name('politica.')->group(function(){
			Route::get('/','PoliticaController@index')->name('index');
			Route::put('/{id}','PoliticaController@update')->name('update');
		});

		Route::prefix('faq')->name('faq.')->group(function(){
			Route::get('/','FaqController@index')->name('index');
			Route::get('nueva','FaqController@create')->name('create');
			Route::post('/','FaqController@store')->name('store');
			Route::get('{id}','FaqController@edit')->name('edit');
			Route::put('{id}','FaqController@update')->name('update');
			Route::delete('/','FaqController@destroy')->name('delete');
		});

		Route::prefix('dimension')->name('size.')->group(function(){
			Route::get('/','CategTamanoController@index')->name('index');
			Route::post('/','CategTamanoController@store')->name('store');
			Route::delete('/','CategTamanoController@destroy')->name('delete');

			Route::name('dimension.')->group(function(){
				Route::get('{slug}','SizeController@index')->name('index');
				Route::post('t','SizeController@store')->name('store');
				Route::delete('t','SizeController@destroy')->name('delete');
			});
		});

		Route::prefix('cupones')->name('cupons.')->group(function(){
			Route::get('/','CuponController@index')->name('index');
		});

	});

	Route::prefix('productos')->name('productos.')->group(function(){
		Route::get('/','ProductoController@index')->name('index');
		Route::get('nuevo','ProductoController@create')->name('create');
		Route::post('nuevo','ProductoController@store')->name('store');
		Route::get('detalle/{id}','ProductoController@show')->name('show');
		Route::get('{id}','ProductoController@edit')->name('edit');
		Route::put('{id}','ProductoController@update')->name('update');
		Route::post('delete','ProductoController@destroy')->name('delete');

		Route::name('pic.')->group(function(){
			Route::post('newpic/{id}','ProductosPhotoController@store')->name('store');
			Route::delete('/','ProductosPhotoController@destroy')->name('delete');
		});

		Route::name('version.')->group(function(){
			Route::post('newpv/{id}','ProductoVersionPhotoController@store')->name('store');
			Route::delete('pv/','ProductoVersionPhotoController@destroy')->name('delete');
		});

		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','ProductoRelacionController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});
	});


		Route::prefix('galeriasub')->name('galeriasub.')->group(function(){
			Route::delete('/','GaleriaSubastaController@destroy')->name('delete');
		});

	/*Route::prefix('config2')->name('config2.')->group(function(){
		Route::get('/','Configuracion2Controller@index')->name('index');
		Route::get('nuevo','Configuracion2Controller@create')->name('create');
		Route::post('/','Configuracion2Controller@store')->name('store');
		Route::get('/{id}','Configuracion2Controller@show')->name('show');
	});*/

	Route::prefix('categorias')->name('categ.')->group(function(){
		Route::get('/','CategoriaController@index')->name('index');
		Route::post('/','CategoriaController@store')->name('store');
		Route::get('/{id}','CategoriaController@show')->name('show');
	});

	Route::prefix('subastas')->name('subastas.')->group(function(){
		Route::get('/','SubastaController@index')->name('index');

resources/views/configs/spaces/index.blade.php
@extends('layouts.admin')

@section('cssExtras')
	<link rel="stylesheet" href="{{asset('css/dropify.css')}}">
@endsection
@section('styleExtras')
<style>
	.card-img-top{
		max-height: 200px;
		object-fit: cover;
	}
</style>
@endsection
@section('content')
	<div class="row mb-2 px-2">
		<a href="{{ route('config.index') }}" class="col col-md-2 btn btn-sm grey darken-2 text-white mr-auto"><i class="fa fa-reply"></i> Regresar</a>
	</div>
	<div class="row">
		<div class="col-12 p-2">
			<div class="card h-100">
				<form action="{{ route('config.space.store') }}" class="card-body mb-0" method="post" enctype="multipart/form-data">
					@csrf
					<input type="hidden" name="imagen" value="1">

					<h5 class="card-title text-center">Agregar Imagen</h5>
					<div class="form-group">
						<label for="name">Imagen</label>
						<input type="file" id="space" name="space" class="dropify"  data-weight="7em" data-height="7em" required />
						<div class="text-center">
							<small class="text-muted">Dimensiones sugeridas: 1900 x 700 px</small>
						</div>
					</div>
					<div class="form-group text-center">
						<button class="btn btn-primary">Guardar</button>
					</div>
				</form>
			</div>
		</div>
		{{-- <div class="col-12 col-lg p-2">
			<div class="card h-100">
				<div class="card-body">
					<h5 class="card-title text-center">Configuración de sliders</h5>

				</div>
			</div>
		</div> --}}
	</div>
	<div class="row mt-3 sortable" data-table="Carrusel">
		@foreach ($espacios as $space)
			<div class="col-12 col-md-3 col-lg-3 my-2 my-md-1 p-2" data-card="{{$space->id}}">
				<div class="card h-100">
					<div class="d-flex justify-content-end">

						<button class="btn btn-sm bg-danger position-absolute text-center text-white" type="button" data-toggle="modal" data-target="#frameModalDel" data-id="{{$space->id}}" style="z-index: 2;">
							<i class="fa fa-trash-alt "></i>
						</button>
						{{-- <a href="" class="bg-danger position-absolute text-center text-white m-2 m-md-1 delslide" style="width:25px;height: auto;border-radius:50%;">
							<i class="fa fa-trash-alt p-1"></i>
						</a> --}}

					</div>
					<a class="btn btn-sm bg-primary position-absolute text-center text-white" href="{{route('config.space.show',$space->id)}}" style="z-index: 2;">
							<i class="fas fa-search"></i>
					</a>

					@if ($space->image)
					<a href="{{asset('/img/photos/espacios/'.$space->image)}}" target="_blank">
						<img src="{{asset('/img/photos/espacios/'.$space->image)}}" class="card-img-top" alt="{{$space->image}}">
					</a>
					@endif
					<div class="card-body p-2">
						<div class="text-center mb-1">
							<small><label class="mb-0" for="titulo">Titulo</label></small>
							<input type="text" name="titulo" id="titulo" class="form-control form-control-sm editarajax" data-id="{{$space->id}}" data-table="espacio" data-campo="titulo"  value="{{ $space->titulo }}">
						</div>
						<div class="text-center mb-1">
							<small><label class="mb-0" for="subtitulo">Descripcion</label></small>
							<textarea name="subtitulo" id="subtitulo" class="form-control form-control-sm editarajax" data-id="{{$space->id}}" data-table="espacio" data-campo="subtitulo"> {{ $space->subtitulo }}</textarea>
						</div>
					</div>
				</div>
			</div>
		@endforeach
	</div>

<div class="modal fade bottom" id="frameModalDel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-frame modal-top" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="row d-flex justify-content-center align-items-center">
					<p class="pt-3 pr-2">
						Eliminar Imagen?
					</p>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
					<button type="button" class="btn red darken-3 text-white delslide">Eliminar</button>
					<form id="colordel" action="{{ route('config.space.delete') }}" method="POST" style="display: none;">
							@csrf
							 @method('delete')
							<input type="hidden" id="isdel" name="space" value="">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('jsLibExtras2')
<script src="{{asset('js/dropify.js')}}" charset="utf-8"></script>

@endsection
@section('jqueryExtra')
<script type="text/javascript">
		$(document).ready(function() {
			$('.dropify').dropify();

			$('.fa-trash-alt').parent().click(function(e) {
				var id = $(this).attr('data-id');
				$("#isdel").val(id);
			});

			$('.delslide').click(function(e) {
				$('#colordel').submit();
			});

		});
	</script>
@endsection

resources/views/configs/spaces/show.blade.php
@extends('layouts.admin')

@section('cssExtras')
	<link rel="stylesheet" href="{{asset('css/dropify.css')}}">
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('styleExtras')
@section('jsLibExtras')
@endsection
<style>
	.card-img-top{
		max-height: 200px;
		object-fit: cover;
	}
</style>
@endsection
@section('content')
	<div class="row mb-2 px-2">
		<a href="{{ route('config.index') }}" class="col col-md-2 btn btn-sm grey darken-2 text-white mr-auto"><i class="fa fa-reply"></i> Regresar</a>
	</div>

	<div>

		<div class="card">
		  	<div class="card-header text-center">
		    	{{$space->titulo}}
		  	</div>
		  	<div class="card-body">

		  		<div class="row">
		  			<div class="col-md-6">
		  				<p class="card-text">{{$space->subtitulo}}</p>
		  			</div>
		  			<div class="col-md-6">
		  				 <img class="img-fluid" src="{{asset('/img/photos/espacios/'. $space->image)}}">
		  			</div>
		  			<div class="col-md-12">
					  	<div class="card mt-3">
						<form action="{{ route('config.rel.update',$space->id) }}" id="fphoto" class="card-body text-center" method="post">
							<h5 class="card-title text-center"> Productos Relacionados</h5>
							@csrf
							@method('put')
							<input type="hidden" name="espacio" value="{{$space->id}}">
							<select name="relacion[]" id="relacion" class="form-control select2" multiple>
								<option disabled></option>
								@foreach ($productos as $p)
								<option @if (in_array($p->id,$space->rel)) selected @endif value="{{$p->id}}">{{$p->titulo_es}}</option>
								@endforeach
							</select>
							<input type="submit" value="Guardar" class="btn btn-primary mt-2">
						</form>
					</div>
		  			</div>
		  		</div>

		  	</div>
		</div>
	</div>
@endsection

@section('jsLibExtras2')
<script src="{{asset('js/dropify.js')}}" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
@endsection
@section('jqueryExtra')
	<script type="text/javascript">
		$(document).ready(function(){
			$('.select2').select2();

			$('.fa-trash-alt').parent().click(function(e) {
				var id = $(this).attr('data-id');
				$("#ipdel").val(id);
			});

			$('.delphoto').click(function(e) {
				$('#photodel').submit();
			});

			// $('#foto').change(function(e) {
			// 	// var drEvent = $('.dropify').dropify();
			//
			// 	drEvent.on('dropify.errors', function(event, element){
			// 		console.log(element);
			// 	});
			// 	// console.log('cambio');
			// 	// $('#fphoto').submit();
			// });
		});
	</script>
@endsection