routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('front.')->group(function(){
	// Route::get('index','FrontController@index')->name('index');
	Route::get('/','FrontController@index')->name('index');
	Route::get('subastas','FrontController@subastas')->name('subastas');
	Route::get('subasta/{id}','FrontController@subasta')->name('subasta');
	Route::get('nosotros','FrontController@aboutus')->name('aboutus');
	//Route::get('espacios','FrontController@espacios')->name('espacios');
	Route::get('espacio/{id}','FrontController@espacio')->name('espacio');
	Route::get('productos/{slug?}','FrontController@productos')->name('productos');
	Route::get('producto/{id}','FrontController@producto')->name('producto');
	Route::get('contacto','FrontController@contact')->name('contact');
	Route::post('contacto','FrontController@mailcontact')->name('mailcontact');
	Route::get('garantias','FrontController@garantias')->name('garantias');
	Route::get('aviso-de-privacidad','FrontController@aviso')->name('aviso');
	Route::get('metodos-de-pago','FrontController@pagos')->name('pagos');
	Route::get('devoluciones','FrontController@devoluciones')->name('devoluciones');
	Route::get('terminos-y-condiciones','FrontController@tyc')->name('tyc');
	Route::get('faq','FrontController@preguntas')->name('faq');
	Route::post('puja','PujaController@store')->name('puja.store');
	Route::post('newslatter','NewslatterController@store')->name('save');
});

// vistas del dashboard del usuario
Route::prefix('dashboard')->name('dash.')->group(function(){
	Route::get('/','HomeController@index')->name('index');
	Route::get('subastas','HomeController@subastas')->name('subastas');
	Route::get('subasta/detalle/{id}','HomeController@subastaDetail')->name('subastaDetail');
	Route::get('perfil','HomeController@perfil')->name('perfil');
	Route::post('update','HomeController@updatePass')->name('updatePass');

	Route::prefix('mis-compras')->name('compras.')->group(function(){
		Route::get('/','HomeController@compras')->name('index');
		Route::get('detalle/{id}','HomeController@detalle')->name('detalle');
	});

	Route::name('profile.')->group(function(){
		Route::post('store','DomicilioController@store')->name('store');
	});


	Route::get('orden/{uuid}','HomeController@orden')->name('orden');
	Route::get('orden-sub/{uuid}','HomeController@ordenSub')->name('ordenSub');
});

Route::prefix('paypal')->name('paypal.')->group(function(){
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPal')->name('paypalpay');
	Route::get('/status', 'PaymentController@payPalStatus')->name('paypalstatus');
	Route::get('/pay/{uid}', 'PaymentController@payWithPayPalSub')->name('paypalpay2');
});

Route::prefix('conekta')->name('conekta.')->group(function(){
	Route::get('/{uid}', 'Payment2Controller@getCard')->name('card');
	Route::post('payment', 'Payment2Controller@statusPay')->name('statusPay');
	// Route::get('/pay/{uid}', 'PaymentController@payWithConekta')->name('conektapay');
	// Route::get('/status', 'PaymentController@conektaStatus')->name('conektastatus');
});

// Route::get('/', function () {
//     return view('layouts.front');
// });

// rutas al admin
Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::name('admin.')->group(function(){
		Route::get('/', 'HomeController@index')->name('home');
		Route::namespace('Auth')->group(function(){
			Route::get('/login', 'LoginController@showLoginForm')->name('login');
			Route::post('/login', 'LoginController@login');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
	});

// rutas al admin configuraciones
// controllers dentro de Controllers/Admin/
	Route::prefix('config')->name('config.')->group(function(){
		Route::get('index','ConfiguracionController@index')->name('index');
		Route::get('general','ConfiguracionController@general')->name('general');
		Route::get('contacto','ConfiguracionController@contact')->name('contact');
		Route::get('textos','ConfiguracionController@textos')->name('textos');
		Route::get('nosotros','ConfiguracionController@about')->name('about');
		Route::put('nosotros/{id}','ConfiguracionController@aboutimg')->name('aboutimg');
		Route::post('nosotros','ConfiguracionController@aboutgal')->name('aboutgal');
		Route::get('subasta','ConfiguracionController@subastagal')->name('subastagal');
		Route::post('subasta','ConfiguracionController@savesubastagal')->name('savesubastagal');



	});
	// Route::prefix('config')->name('config.')->group(function(){
	// 	Route::get('index','ConfiguracionController@index')->name('index');
	// });
});

// rutas al admin configuraciones
// controllers dentro de Controllers/
Route::prefix('admin')->group(function(){
	Route::prefix('config')->name('config.')->group(function(){
		Route::prefix('colores')->name('color.')->group(function(){
			Route::get('/','ColorController@index')->name('index');
			Route::post('/','ColorController@store')->name('store');
			Route::get('editar/{id}','ColorController@edit')->name('edit');
			Route::put('{id}','ColorController@update')->name('update');
			Route::delete('/','ColorController@destroy')->name('delete');
		});

		Route::prefix('sliders')->name('slider.')->group(function(){
			Route::get('/','CarruselController@index')->name('index');
			Route::post('/','CarruselController@store')->name('store');
			Route::delete('/','CarruselController@destroy')->name('delete');
		});



		Route::prefix('spaces')->name('space.')->group(function(){
			Route::get('/','EspacioController@index')->name('index');
			Route::get('detalle/{id}','EspacioController@show')->name('show');
			Route::post('/','EspacioController@store')->name('store');
			Route::delete('/','EspacioController@destroy')->name('delete');

		});

		Route::prefix('sucursales')->name('sucursal.')->group(function(){
			Route::get('/','SucursalController@index')->name('index');
			Route::get('nueva','SucursalController@create')->name('create');
			Route::post('/','SucursalController@store')->name('store');
			Route::get('{id}','SucursalController@edit')->name('edit');
			Route::put('{id}','SucursalController@update')->name('update');
			Route::delete('/','SucursalController@destroy')->name('delete');

		});


		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','EspacioproductoController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});

		Route::prefix('politicas')->name('politica.')->group(function(){
			Route::get('/','PoliticaController@index')->name('index');
			Route::put('/{id}','PoliticaController@update')->name('update');
		});

		Route::prefix('faq')->name('faq.')->group(function(){
			Route::get('/','FaqController@index')->name('index');
			Route::get('nueva','FaqController@create')->name('create');
			Route::post('/','FaqController@store')->name('store');
			Route::get('{id}','FaqController@edit')->name('edit');
			Route::put('{id}','FaqController@update')->name('update');
			Route::delete('/','FaqController@destroy')->name('delete');
		});

		Route::prefix('dimension')->name('size.')->group(function(){
			Route::get('/','CategTamanoController@index')->name('index');
			Route::post('/','CategTamanoController@store')->name('store');
			Route::delete('/','CategTamanoController@destroy')->name('delete');

			Route::name('dimension.')->group(function(){
				Route::get('{slug}','SizeController@index')->name('index');
				Route::post('t','SizeController@store')->name('store');
				Route::delete('t','SizeController@destroy')->name('delete');
			});
		});

		Route::prefix('cupones')->name('cupons.')->group(function(){
			Route::get('/','CuponController@index')->name('index');
		});

	});

	Route::prefix('productos')->name('productos.')->group(function(){
		Route::get('/','ProductoController@index')->name('index');
		Route::get('nuevo','ProductoController@create')->name('create');
		Route::post('nuevo','ProductoController@store')->name('store');
		Route::get('detalle/{id}','ProductoController@show')->name('show');
		Route::get('{id}','ProductoController@edit')->name('edit');
		Route::put('{id}','ProductoController@update')->name('update');
		Route::post('delete','ProductoController@destroy')->name('delete');

		Route::name('pic.')->group(function(){
			Route::post('newpic/{id}','ProductosPhotoController@store')->name('store');
			Route::delete('/','ProductosPhotoController@destroy')->name('delete');
		});

		Route::name('version.')->group(function(){
			Route::post('newpv/{id}','ProductoVersionPhotoController@store')->name('store');
			Route::delete('pv/','ProductoVersionPhotoController@destroy')->name('delete');
		});

		Route::name('rel.')->group(function(){
			Route::put('rel/{id}','ProductoRelacionController@update')->name('update');
			// Route::delete('rel/','ProductoRelacionController@destroy')->name('delete');
		});
	});


		Route::prefix('galeriasub')->name('galeriasub.')->group(function(){
			Route::delete('/','GaleriaSubastaController@destroy')->name('delete');
		});

	/*Route::prefix('config2')->name('config2.')->group(function(){
		Route::get('/','Configuracion2Controller@index')->name('index');
		Route::get('nuevo','Configuracion2Controller@create')->name('create');
		Route::post('/','Configuracion2Controller@store')->name('store');
		Route::get('/{id}','Configuracion2Controller@show')->name('show');
	});*/

	Route::prefix('categorias')->name('categ.')->group(function(){
		Route::get('/','CategoriaController@index')->name('index');
		Route::post('/','CategoriaController@store')->name('store');
		Route::get('/{id}','CategoriaController@show')->name('show');
	});

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
			'pregunta','respuesta','orden',
	];
}

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\Faq;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
			$faqs = Faq::orderBy('orden','asc')->get();
			return view('configs.faqs.index', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		return view('configs.faqs.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
			$validate = Validator::make($request->all(),[
					'question' => 'required',
					'answer' => 'required',
				],[],[
					'question' => 'pregunta',
					'answer' => 'respuesta',
				]);

			if ($validate->fails()) {
				\Toastr::error('Error, se requieren mas datos');
				return redirect()->back();
			}
			$faq = new Faq;

			$faq->pregunta = $request->question;
			$faq->respuesta = $request->answer;

			$faq->save();
			\Toastr::success('Guardado');
			return redirect()->route('config.faq.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function show(Faq $faq)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function edit($faq){
			$faq = Faq::find($faq);

			if (empty($faq)) {
				\Toastr::error('Error al buscar, intente mas tarde');
				return redirect()->back();
			}
			return view('configs.faqs.edit',compact('faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
			$faq = Faq::find($id);

			$validate = Validator::make($request->all(),[
					'question' => 'required',
					'answer' => 'required',
				],[],[
					'question' => 'pregunta',
					'answer' => 'respuesta',
				]);

			if ($validate->fails()) {
				\Toastr::error('Error, se requieren mas datos');
				return redirect()->back();
			}

			if (empty($faq)) {
				\Toastr::error('Error al buscar, intente mas tarde');
				return redirect()->back();
			}

			$faq->pregunta = $request->question;
			$faq->respuesta = $request->answer;

			$faq->save();

			\Toastr::success('Guardado Exitosamente');
			return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request){
			if (empty($request->pregunta)) {
				\Toastr::error('Error, intentalo mas tarde');
				return redirect()->back();
			}

			$faq = Faq::find($request->pregunta);

			$faq->delete();
			\Toastr::success('Eliminado Exitosamente');
			return redirect()->back();
    }
}

resources/views/configs/faqs/create.blade.php
@extends('layouts.admin')

@section('cssExtras')
@endsection

@section('jsLibExtras')
@endsection

@section('content')
	<div class="row mb-4 px-2">
		<a href="{{ route('config.index') }}" class="col col-md-2 btn btn-sm grey darken-2 text-white mr-auto"><i class="fa fa-reply"></i> Regresar</a>
	</div>

	<div class="col-12 col-md-8 mx-auto">
		<div class="card">
			<div class="card-body">
				<form action="{{ route('config.sucursal.store') }}" method="post">
					@csrf
					<div class="form-group">
						<label for="question">Pregunta</label>
						<input type="text" name="question" id="question" class="form-control">
					</div>
					<div class="form-group">
						<label for="answer">Respuesta</label>
						<textarea name="answer" id="answer" rows="10" class="texteditor form-control" style="resize:none;"></textarea>
					</div>
					<div class="form-group text-center">
						<button type="submit" class="btn btn-primary">Guardar</button>
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection
@section('jsLibExtras2')
	<script>
	    tinymce.init({
	      selector: 'textarea',
	      // plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
	      // toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
				menubar: false,
			  plugins: [
			    'advlist autolink lists link image charmap print preview anchor',
			    'searchreplace visualblocks code fullscreen',
			    'insertdatetime media table paste code help wordcount',
					'advlist autolink lists link image charmap print preview anchor wordcount',

					'searchreplace visualblocks code fullscreen table visualblocks',
					'insertdatetime media table contextmenu paste code imagetools',
					'textcolor colorpicker'
			  ],
			  // toolbar: 'undo redo | formatselect | ' +
			  // 'bold italic backcolor | alignleft aligncenter ' +
			  // 'alignright alignjustify | bullist numlist outdent indent | ' +
			  // 'removeformat | help',
				toolbar: 'forecolor backcolor | insert table | undo redo | removeformat styleselect |  bold italic underline |  alignleft aligncenter alignright alignjustify |  bullist numlist | outdent indent | link image | code visualblocks',
				resize: false,
			  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
	   });
	  </script>
@endsection

resources/views/configs/faqs/edit.blade.php
@extends('layouts.admin')

@section('cssExtras')
@endsection

@section('jsLibExtras')
@endsection

@section('content')
	<div class="row mb-4 px-2">
		<a href="{{ route('config.index') }}" class="col col-md-2 btn btn-sm grey darken-2 text-white mr-auto"><i class="fa fa-reply"></i> Regresar</a>
	</div>

	<div class="col-12 col-md-8 mx-auto">
		<div class="card">
			<div class="card-body">
				<form action="{{ route('config.faq.update',$faq->id) }}" method="post">
					@csrf
					@method('put')
					<div class="form-group">
						<label for="question">Pregunta</label>
						<input type="text" name="question" id="question" class="form-control" value="{{$faq->pregunta}}">
					</div>
					<div class="form-group">
						<label for="answer">Respuesta</label>
						<textarea name="answer" id="answer" rows="10" class="texteditor form-control" style="resize:none;">{{ $faq->respuesta }}</textarea>
					</div>
					<div class="form-group text-center">
						<button type="submit" class="btn btn-primary">Guardar</button>
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection
@section('jsLibExtras2')
	<script>
	    tinymce.init({
	      selector: 'textarea',
	      // plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
	      // toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
				menubar: false,
			  plugins: [
			    'advlist autolink lists link image charmap print preview anchor',
			    'searchreplace visualblocks code fullscreen',
			    'insertdatetime media table paste code help wordcount',
					'advlist autolink lists link image charmap print preview anchor wordcount',

					'searchreplace visualblocks code fullscreen table visualblocks',
					'insertdatetime media table contextmenu paste code imagetools',
					'textcolor colorpicker'
			  ],
			  // toolbar: 'undo redo | formatselect | ' +
			  // 'bold italic backcolor | alignleft aligncenter ' +
			  // 'alignright alignjustify | bullist numlist outdent indent | ' +
			  // 'removeformat | help',
				toolbar: 'forecolor backcolor | insert table | undo redo | removeformat styleselect |  bold italic underline |  alignleft aligncenter alignright alignjustify |  bullist numlist | outdent indent | link image | code visualblocks',
				resize: false,
			  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
	   });
	  </script>
@endsection

resources/views/configs/faqs/index.blade.php
@extends('layouts.admin')

@section('cssExtras')
@endsection

@section('jsLibExtras')
@endsection

@section('content')
	<div class="row mb-2 px-2">
		<a href="{{ route('config.index') }}" class="col col-md-2 btn btn-sm grey darken-2 text-white mr-auto"><i class="fa fa-reply"></i> Regresar</a>
		<a href="{{ route('config.faq.create') }}" class="col col-md-2 btn btn-sm green darken-2 text-white"><i class="fa fa-plus"></i> Agregar</a>
	</div>

	<div class="accordion sortable" data-table="Faq" id="acordionfaqs">
		@foreach ($faqs as $f)
			<div class="card mb-3" data-card="{{$f->id}}">
				<div class="card-header grey lighten-4 row" id="heading{{$f->id}}">
					<h2 class="mb-0 w-75">
						<button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{$f->id}}" aria-expanded="true" aria-controls="collapse{{$f->id}}">
							{{ $f->pregunta}}
						</button>
					</h2>
					<div class="mb-0 w-25 text-right">
						<div class="btn-group btn-group-sm" role="group" aria-label="...">
							<a href="{{route('config.faq.edit',$f->id)}}" class="btn btn-sm btn-info text-right">
								<i class="fas fa-pen"></i>
							</a>
							<button class="btn btn-sm btn-danger text-right" data-toggle="modal" data-target="#frameModalDel" data-id="{{$f->id}}">
								<i class="fas fa-trash-alt"></i>
							</button>
						</div>
					</div>
				</div>

				<div id="collapse{{$f->id}}" class="collapse" aria-labelledby="heading{{$f->id}}" data-parent="#acordionfaqs">
					<div class="card-body text-justify">
						{!! $f->respuesta!!}
					</div>
				</div>
			</div>
		@endforeach
	</div>

	<div class="modal fade bottom" id="frameModalDel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-frame modal-top" role="document">
			<div class="modal-content">
				<div class="modal-body">
					<div class="row d-flex justify-content-center align-items-center">
						<p class="pt-3 pr-2">
							Eliminar Pregunta?
						</p>
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
						<button type="button" class="btn red darken-3 text-white delslide">Eliminar</button>
						<form id="preguntadel" action="{{ route('config.faq.delete') }}" method="POST" style="display: none;">
								@csrf
								 @method('delete')
								<input type="hidden" id="iqdel" name="pregunta" value="">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection
@section('jqueryExtra')
	<script type="text/javascript">
		$(document).ready(function() {

			$('.fa-trash-alt').parent().click(function(e) {
				var id = $(this).attr('data-id');
				$("#iqdel").val(id);
			});

			$('.delslide').click(function(e) {
				$('#preguntadel').submit();
			});

		});
	</script>
@endsection